# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.6
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - target/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
