database_name: null
database_host: null
database_username: null
database_password: null
aws:
  access_key_id: null
  secret_access_key: null
  bucket: null
  region: null
rswag:
  username: null
  password: null
  host: null
redis:
  url: null
secret_key_base: null
admin:
  email: null
  password: null
cookie_store_key: null
gmail_smtp:
  domain: null
  email: null
  app_password: null
sentry_dsn: null
sidekiq:
  server_url: null
  client_url: null
