default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch('POSTGRES_DB', Rails.application.credentials.dig(:database_name)) %>
  host: <%= ENV.fetch('POSTGRES_HOST', Rails.application.credentials.dig(:database_host)) %>
  username: <%= ENV.fetch('POSTGRES_USER', Rails.application.credentials.dig(:database_username)) %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', Rails.application.credentials.dig(:database_password)) %>


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
